version: "2"

services:
  flask-app:
    build:
      - context: .
      - dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'