version: '3'

services:
  flask-app:
     build: .
     ports:
        - "80:80"
     volumes:
        - .:/prj
     environment:
        - FLASK_APP=./app/main.py
        - 'RUN=flask run --host=0.0.0.0 --port=80'