version: '3'

services:
  flask-app:
     build: .
     ports:
        - "7777:7777"
     volumes:
        - .:/app
     environment:
        - FLASK_APP=main.py
        - 'RUN=flask run --host=0.0.0.0 --port=7777'